"""adding IR to game stat options

Revision ID: 2bb3322a6c75
Revises: e20b3d617b73
Create Date: 2023-09-02 09:56:30.754769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb3322a6c75'
down_revision: Union[str, None] = 'e20b3d617b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qb_game_stats', sa.Column('ir', sa.Boolean(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('ir', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_game_stats', 'ir')
    op.drop_column('qb_game_stats', 'ir')
    # ### end Alembic commands ###
