"""init

Revision ID: 367109604093
Revises: ca08294efce9
Create Date: 2023-09-01 15:31:20.361705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367109604093'
down_revision: Union[str, None] = 'ca08294efce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qb_game_stats', sa.Column('opp', sa.String(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('opp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_game_stats', 'opp')
    op.drop_column('qb_game_stats', 'opp')
    # ### end Alembic commands ###
