"""Update GameStats model

Revision ID: 3e59e97ee8ec
Revises: 76d1ed47ff75
Create Date: 2024-08-02 00:06:32.093631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e59e97ee8ec'
down_revision: Union[str, None] = '76d1ed47ff75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stats', sa.Column('rushing_yards', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_stats', 'rushing_yards')
    # ### end Alembic commands ###
