"""renaming suspended

Revision ID: 53b5aea78dfd
Revises: 2bb3322a6c75
Create Date: 2023-09-02 10:37:07.366888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b5aea78dfd'
down_revision: Union[str, None] = '2bb3322a6c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qb_game_stats', sa.Column('suspended', sa.Boolean(), nullable=True))
    op.drop_column('qb_game_stats', 'player_suspended')
    op.add_column('skill_game_stats', sa.Column('suspended', sa.Boolean(), nullable=True))
    op.drop_column('skill_game_stats', 'player_suspended')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_game_stats', sa.Column('player_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('skill_game_stats', 'suspended')
    op.add_column('qb_game_stats', sa.Column('player_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('qb_game_stats', 'suspended')
    # ### end Alembic commands ###
