"""removing extra pos

Revision ID: 6915ab85753f
Revises: 9753f6b19c01
Create Date: 2023-08-31 22:39:19.768967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6915ab85753f'
down_revision: Union[str, None] = '9753f6b19c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('weight_lb', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('drafted_overall', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('college', sa.String(), nullable=True))
    op.drop_column('players', 'pos_alt')
    op.drop_column('players', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('age', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('pos_alt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('players', 'college')
    op.drop_column('players', 'drafted_overall')
    op.drop_column('players', 'weight_lb')
    op.drop_column('players', 'height_cm')
    op.drop_column('players', 'dob')
    # ### end Alembic commands ###
