"""adding away game

Revision ID: 7a8e46529924
Revises: de406079898e
Create Date: 2023-09-01 13:24:00.113822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8e46529924'
down_revision: Union[str, None] = 'de406079898e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.drop_column('players', 'weight_lb')
    op.add_column('qb_game_stats', sa.Column('away_game', sa.Boolean(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('away_game', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_game_stats', 'away_game')
    op.drop_column('qb_game_stats', 'away_game')
    op.add_column('players', sa.Column('weight_lb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players', 'weight_kg')
    # ### end Alembic commands ###
