"""init migration

Revision ID: 8f11e665f99b
Revises: 
Create Date: 2023-08-31 15:12:01.585086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f11e665f99b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('drafted_year', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('pos_alt', sa.String(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('snaps', sa.Integer(), nullable=True),
    sa.Column('snap_perc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.Boolean(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('off_total', sa.Float(), nullable=True),
    sa.Column('off_pass', sa.Float(), nullable=True),
    sa.Column('off_rush', sa.Float(), nullable=True),
    sa.Column('off_exp_turn', sa.Float(), nullable=True),
    sa.Column('def_tot', sa.Float(), nullable=True),
    sa.Column('def_pass', sa.Float(), nullable=True),
    sa.Column('def_rush', sa.Float(), nullable=True),
    sa.Column('def_exp_turn', sa.Float(), nullable=True),
    sa.Column('first_downs', sa.Integer(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('rush_tds', sa.Integer(), nullable=True),
    sa.Column('rush_yds', sa.Integer(), nullable=True),
    sa.Column('pass_att', sa.Integer(), nullable=True),
    sa.Column('pass_comp', sa.Integer(), nullable=True),
    sa.Column('pass_yds', sa.Integer(), nullable=True),
    sa.Column('pass_tds', sa.Integer(), nullable=True),
    sa.Column('pass_int', sa.Integer(), nullable=True),
    sa.Column('sack_yds', sa.Integer(), nullable=True),
    sa.Column('total_yds', sa.Integer(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('fumbles_lost', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('penalty_yds', sa.Integer(), nullable=True),
    sa.Column('time_of_pos', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('away_team_stats_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('home_team_stats_id', sa.Integer(), nullable=True),
    sa.Column('roof', sa.String(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('Weather', sa.String(), nullable=True),
    sa.Column('over_under', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_stats_id'], ['team_game_stats.id'], ),
    sa.ForeignKeyConstraint(['home_team_stats_id'], ['team_game_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qb_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qb_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pass_comp', sa.Integer(), nullable=True),
    sa.Column('pass_att', sa.Integer(), nullable=True),
    sa.Column('pass_yds', sa.Integer(), nullable=True),
    sa.Column('pass_tds', sa.Integer(), nullable=True),
    sa.Column('pass_ints', sa.Integer(), nullable=True),
    sa.Column('pass_first_downs', sa.Integer(), nullable=True),
    sa.Column('pass_first_down_perc', sa.Float(), nullable=True),
    sa.Column('pass_IAY', sa.Integer(), nullable=True),
    sa.Column('pass_CAY', sa.Integer(), nullable=True),
    sa.Column('pass_drops', sa.Integer(), nullable=True),
    sa.Column('pass_bad_throw', sa.Integer(), nullable=True),
    sa.Column('pass_bad_throw_perc', sa.Float(), nullable=True),
    sa.Column('pass_pressure_perc', sa.Float(), nullable=True),
    sa.Column('pass_sacks', sa.Integer(), nullable=True),
    sa.Column('pass_per_att', sa.Integer(), nullable=True),
    sa.Column('pass_adj_per_att', sa.Integer(), nullable=True),
    sa.Column('rush_first_downs', sa.Integer(), nullable=True),
    sa.Column('rush_ybc', sa.Integer(), nullable=True),
    sa.Column('rush_yac', sa.Integer(), nullable=True),
    sa.Column('rush_brkTkl', sa.Integer(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('rush_yds', sa.Integer(), nullable=True),
    sa.Column('rush_per_att', sa.Float(), nullable=True),
    sa.Column('rush_tds', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('rec_first_downs', sa.Integer(), nullable=True),
    sa.Column('rec_ybc', sa.Integer(), nullable=True),
    sa.Column('rec_yac', sa.Integer(), nullable=True),
    sa.Column('rec_adot', sa.Float(), nullable=True),
    sa.Column('rec_brkTkl', sa.Integer(), nullable=True),
    sa.Column('rec_drop', sa.Integer(), nullable=True),
    sa.Column('rec_int', sa.Integer(), nullable=True),
    sa.Column('rec_tgt', sa.Integer(), nullable=True),
    sa.Column('rec_rec', sa.Integer(), nullable=True),
    sa.Column('rec_yds', sa.Integer(), nullable=True),
    sa.Column('rec_per_rec', sa.Integer(), nullable=True),
    sa.Column('rec_tds', sa.Integer(), nullable=True),
    sa.Column('rush_first_downs', sa.Integer(), nullable=True),
    sa.Column('rush_ybc', sa.Integer(), nullable=True),
    sa.Column('rush_yac', sa.Integer(), nullable=True),
    sa.Column('rush_brkTkl', sa.Integer(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('rush_yds', sa.Integer(), nullable=True),
    sa.Column('rush_per_att', sa.Float(), nullable=True),
    sa.Column('rush_tds', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['skill_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_game_stats')
    op.drop_table('qb_game_stats')
    op.drop_table('skill_player')
    op.drop_table('qb_player')
    op.drop_table('game')
    op.drop_table('team_game_stats')
    op.drop_table('players')
    # ### end Alembic commands ###
