"""update to game stats to reflect pfr

Revision ID: 8faa644c53cc
Revises: 8f11e665f99b
Create Date: 2023-08-31 20:52:06.241276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8faa644c53cc'
down_revision: Union[str, None] = '8f11e665f99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qb_game_stats', sa.Column('age', sa.Float(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('bye', sa.Boolean(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('inactive', sa.Boolean(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('dnp', sa.Boolean(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('player_suspended', sa.Boolean(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('playoff', sa.Boolean(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('age', sa.Float(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('bye', sa.Boolean(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('inactive', sa.Boolean(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('dnp', sa.Boolean(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('player_suspended', sa.Boolean(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('playoff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_game_stats', 'playoff')
    op.drop_column('skill_game_stats', 'date')
    op.drop_column('skill_game_stats', 'player_suspended')
    op.drop_column('skill_game_stats', 'dnp')
    op.drop_column('skill_game_stats', 'inactive')
    op.drop_column('skill_game_stats', 'bye')
    op.drop_column('skill_game_stats', 'age')
    op.drop_column('qb_game_stats', 'playoff')
    op.drop_column('qb_game_stats', 'date')
    op.drop_column('qb_game_stats', 'player_suspended')
    op.drop_column('qb_game_stats', 'dnp')
    op.drop_column('qb_game_stats', 'inactive')
    op.drop_column('qb_game_stats', 'bye')
    op.drop_column('qb_game_stats', 'age')
    # ### end Alembic commands ###
