"""removeing adv stats, to be added later

Revision ID: 9753f6b19c01
Revises: 8faa644c53cc
Create Date: 2023-08-31 22:21:47.673217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9753f6b19c01'
down_revision: Union[str, None] = '8faa644c53cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qb_game_stats', 'pass_pressure_perc')
    op.drop_column('qb_game_stats', 'pass_bad_throw')
    op.drop_column('qb_game_stats', 'pass_drops')
    op.drop_column('qb_game_stats', 'pass_first_down_perc')
    op.drop_column('qb_game_stats', 'pass_first_downs')
    op.drop_column('qb_game_stats', 'pass_CAY')
    op.drop_column('qb_game_stats', 'pass_IAY')
    op.drop_column('qb_game_stats', 'pass_bad_throw_perc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qb_game_stats', sa.Column('pass_bad_throw_perc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('qb_game_stats', sa.Column('pass_IAY', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qb_game_stats', sa.Column('pass_CAY', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qb_game_stats', sa.Column('pass_first_downs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qb_game_stats', sa.Column('pass_first_down_perc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('qb_game_stats', sa.Column('pass_drops', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qb_game_stats', sa.Column('pass_bad_throw', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qb_game_stats', sa.Column('pass_pressure_perc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
