"""adding many ids to they players

Revision ID: c41b71046f9f
Revises: c57fcfbec225
Create Date: 2024-05-29 15:33:46.421463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41b71046f9f'
down_revision: Union[str, None] = 'c57fcfbec225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('rotoworld_id', sa.String(), nullable=True))
    op.add_column('players', sa.Column('rotowire_id', sa.String(), nullable=True))
    op.add_column('players', sa.Column('yahoo_id', sa.String(), nullable=True))
    op.add_column('players', sa.Column('espn_id', sa.String(), nullable=True))
    op.add_column('players', sa.Column('swish_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'players', ['espn_id'])
    op.create_unique_constraint(None, 'players', ['rotoworld_id'])
    op.create_unique_constraint(None, 'players', ['swish_id'])
    op.create_unique_constraint(None, 'players', ['rotowire_id'])
    op.create_unique_constraint(None, 'players', ['yahoo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'swish_id')
    op.drop_column('players', 'espn_id')
    op.drop_column('players', 'yahoo_id')
    op.drop_column('players', 'rotowire_id')
    op.drop_column('players', 'rotoworld_id')
    # ### end Alembic commands ###
