"""init

Revision ID: ca08294efce9
Revises: 
Create Date: 2023-09-01 14:52:33.317504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca08294efce9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('drafted_year', sa.DateTime(), nullable=True),
    sa.Column('drafted_overall', sa.Integer(), nullable=True),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qb_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('pass_comp', sa.Integer(), nullable=True),
    sa.Column('pass_att', sa.Integer(), nullable=True),
    sa.Column('pass_yds', sa.Integer(), nullable=True),
    sa.Column('pass_tds', sa.Integer(), nullable=True),
    sa.Column('pass_ints', sa.Integer(), nullable=True),
    sa.Column('pass_sacks', sa.Integer(), nullable=True),
    sa.Column('pass_per_att', sa.Integer(), nullable=True),
    sa.Column('pass_adj_per_att', sa.Integer(), nullable=True),
    sa.Column('rush_first_downs', sa.Integer(), nullable=True),
    sa.Column('rush_ybc', sa.Integer(), nullable=True),
    sa.Column('rush_yac', sa.Integer(), nullable=True),
    sa.Column('rush_brkTkl', sa.Integer(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('rush_yds', sa.Integer(), nullable=True),
    sa.Column('rush_per_att', sa.Float(), nullable=True),
    sa.Column('rush_tds', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('away_game', sa.Boolean(), nullable=True),
    sa.Column('bye', sa.Boolean(), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.Column('dnp', sa.Boolean(), nullable=True),
    sa.Column('player_suspended', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('playoff', sa.Boolean(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('snaps', sa.Integer(), nullable=True),
    sa.Column('snap_perc', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('rec_first_downs', sa.Integer(), nullable=True),
    sa.Column('rec_ybc', sa.Integer(), nullable=True),
    sa.Column('rec_yac', sa.Integer(), nullable=True),
    sa.Column('rec_adot', sa.Float(), nullable=True),
    sa.Column('rec_brkTkl', sa.Integer(), nullable=True),
    sa.Column('rec_drop', sa.Integer(), nullable=True),
    sa.Column('rec_int', sa.Integer(), nullable=True),
    sa.Column('rec_tgt', sa.Integer(), nullable=True),
    sa.Column('rec_rec', sa.Integer(), nullable=True),
    sa.Column('rec_yds', sa.Integer(), nullable=True),
    sa.Column('rec_per_rec', sa.Integer(), nullable=True),
    sa.Column('rec_tds', sa.Integer(), nullable=True),
    sa.Column('rush_first_downs', sa.Integer(), nullable=True),
    sa.Column('rush_ybc', sa.Integer(), nullable=True),
    sa.Column('rush_yac', sa.Integer(), nullable=True),
    sa.Column('rush_brkTkl', sa.Integer(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('rush_yds', sa.Integer(), nullable=True),
    sa.Column('rush_per_att', sa.Float(), nullable=True),
    sa.Column('rush_tds', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('away_game', sa.Boolean(), nullable=True),
    sa.Column('bye', sa.Boolean(), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.Column('dnp', sa.Boolean(), nullable=True),
    sa.Column('player_suspended', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('playoff', sa.Boolean(), nullable=True),
    sa.Column('fumbles', sa.Integer(), nullable=True),
    sa.Column('snaps', sa.Integer(), nullable=True),
    sa.Column('snap_perc', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_game_stats')
    op.drop_table('qb_game_stats')
    op.drop_table('players')
    # ### end Alembic commands ###
