"""updating Player to include id from pfr

Revision ID: ddc7c1e3cf1f
Revises: 367109604093
Create Date: 2023-09-01 16:07:05.200363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc7c1e3cf1f'
down_revision: Union[str, None] = '367109604093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('pfr_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'players', ['pfr_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'pfr_id')
    # ### end Alembic commands ###
