"""removing extra pos

Revision ID: de406079898e
Revises: 6915ab85753f
Create Date: 2023-08-31 22:40:35.268924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de406079898e'
down_revision: Union[str, None] = '6915ab85753f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'fumbles')
    op.drop_column('players', 'snap_perc')
    op.drop_column('players', 'snaps')
    op.add_column('qb_game_stats', sa.Column('fumbles', sa.Integer(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('snaps', sa.Integer(), nullable=True))
    op.add_column('qb_game_stats', sa.Column('snap_perc', sa.Float(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('fumbles', sa.Integer(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('snaps', sa.Integer(), nullable=True))
    op.add_column('skill_game_stats', sa.Column('snap_perc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_game_stats', 'snap_perc')
    op.drop_column('skill_game_stats', 'snaps')
    op.drop_column('skill_game_stats', 'fumbles')
    op.drop_column('qb_game_stats', 'snap_perc')
    op.drop_column('qb_game_stats', 'snaps')
    op.drop_column('qb_game_stats', 'fumbles')
    op.add_column('players', sa.Column('snaps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('snap_perc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('fumbles', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
