"""updating player.drafted_year to be an integer instead of dt

Revision ID: e20b3d617b73
Revises: a8bf65847b51
Create Date: 2023-09-01 16:47:27.673232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20b3d617b73'
down_revision: Union[str, None] = 'a8bf65847b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('drafted_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'drafted_year')
    # ### end Alembic commands ###
