"""updating player.drafted_year to be an integer instead of dt

Revision ID: f3195bfd8506
Revises: c5d0fbcdfaf2
Create Date: 2023-09-01 16:46:57.833889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3195bfd8506'
down_revision: Union[str, None] = 'c5d0fbcdfaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
