name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: data_engineering tests
        working-directory: data_engineering
        run: uv run pytest -ra

      - name: machine_learning tests
        working-directory: machine_learning
        run: uv run pytest -ra
